#!/bin/bash

if ! whoami &> /dev/null; then
  if [ -w /etc/passwd ]; then
    echo "${USER_NAME:-default}:x:$(id -u):0:${USER_NAME:-default} user:${HOME}:/sbin/nologin" >> /etc/passwd
  fi
fi

export JAVA_HOME=$(readlink -f /usr/bin/java | sed 's/\/jre\/bin\/java//g')

/wso2/wso2ei-6.4.0/bin/integrator.sh
